**KFOLD WITH DATASETS**

In [93]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits() # classify digits dataset and use different models and evaluate each performance

In [25]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [26]:
lr = LogisticRegression(solver='lbfgs', max_iter=10000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9629629629629629

In [27]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9888888888888889

In [28]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9574074074074074

In [ ]:
#That's the problem with train test split, you run multiple times and get different results

In [30]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3) # fold which separate and test data
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [31]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
#this is how it tests: the test_index is removed from the array, and it is used as
#a training model. for all the iteration, it does the same thing

In [32]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [33]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9888888888888889

In [35]:
from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits=3)

In [54]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(max_iter=100000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [55]:
scores_l

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [56]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [57]:
scores_rf

[0.9298831385642737, 0.9432387312186978, 0.9165275459098498]

In [58]:
from sklearn.model_selection import cross_val_score #does the same thing as iter

In [60]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [62]:
from sklearn.datasets import load_iris
iris = load_iris()

In [83]:
lr = cross_val_score(LogisticRegression(max_iter=100000), iris.data, iris.target)
np.average(lr)

0.9733333333333334

In [84]:
svm = cross_val_score(SVC(), iris.data, iris.target)
np.average(svm)

0.9666666666666666

In [85]:
dt = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
np.average(dt)

0.9666666666666668

In [86]:
rf = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)
np.average(rf)

0.96

**TRAIN WITH DATASETS**

In [98]:
df = pd.read_csv('california_housing_test.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [123]:
x = df.drop(['median_house_value', 'latitude', 'longitude', 'population', 'total_rooms'], axis='columns')
y = df['median_house_value']

In [124]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [125]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [126]:
model.score(X_test, y_test)

0.4821833382153793