In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model

In [ ]:
h = pd.read_csv('homeprices.csv')
h

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
import math

bed_med = math.floor(h.bedrooms.median())
bed_med
#h.drop([5], axis=0, inplace=True)
h

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
h.bedrooms = h.bedrooms.fillna(bed_med)

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(h[['area', 'bedrooms', 'age']], h.price)
reg.coef_ #

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
reg.predict([[3000, 3, 15]]) 

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([579201.19929613])

In [ ]:
df = pd.read_csv('hiring.csv')
df.experience = df.experience.fillna(0)
df.rename(columns={'test_score(out of 10)': 'test_score'}, inplace=True)
df.rename(columns={'salary($)': 'salary'}, inplace=True)
med = math.floor(df.test_score.median())
df.test_score = df.test_score.fillna(7)
df

experience  test_score  interview_score(out of 10)  salary
0         0.0         8.0                           9   50000
1         0.0         8.0                           6   45000
2         5.0         6.0                           7   60000
3         2.0        10.0                          10   65000
4         7.0         9.0                           6   70000
5         3.0         7.0                          10   62000
6        10.0         7.0                           7   72000
7        11.0         7.0                           8   80000

In [ ]:
r = linear_model.LinearRegression()
r.fit(df[['experience', 'test_score', 'interview_score(out of 10)']], df.salary)
reg.coef_ #

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
r.predict([[2, 9, 6]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [ ]:
r.predict([[12, 10, 10]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])